/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";
import Link from "next/link";

export function Header() {
  return (
    <header className="flex w-full items-center justify-between whitespace-nowrap px-px max-md:max-w-full max-md:flex-wrap">
      <div className="relative my-auto aspect-[4.35] w-[161px] max-w-full self-stretch">
        <Image
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/895933121ee3dc90e06c13bf012a41f63aff513b905dc474dda0fe6773f4d166?apiKey=5503bfd9e2fe4e73b2f967c9116ec022&"
          alt="Logo"
          layout="fill"
          objectFit="contain"
        />
      </div>
      <nav className="my-auto flex gap-1 self-stretch text-lg text-white">
        <div className="my-auto h-[17px] w-0.5 bg-green-400" />
        <div className="flex justify-between gap-5">
          <Link href="#" className="grow font-bold">
            Home
          </Link>
          <Link href="#">Sobre</Link>
          <Link href="#">Categorias</Link>
          <Link href="#" className="grow">
            Contato
          </Link>
        </div>
      </nav>
      <div className="flex justify-between gap-0 self-stretch text-sm text-purple-50">
        <button className="grow items-start justify-center rounded bg-slate-900 py-4 pl-7 pr-16 max-md:px-5">
          Buscar
        </button>
        <div className="relative aspect-[1.59] w-[70px]">
          <Image
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/13739dd3c0e01b7aa6f3b60306ab8ade056f6b40c4c53b628355cf2ca400c4d0?apiKey=5503bfd9e2fe4e73b2f967c9116ec022"
            alt="User Profile"
            layout="fill"
            objectFit="contain"
          />
        </div>
      </div>
    </header>
  );
}

export function HeroSection() {
  return (
    <section className="flex w-full gap-5 max-md:flex-col max-md:gap-0">
      <article className="flex w-6/12 flex-col max-md:ml-0 max-md:w-full">
        <h1 className="mt-3 text-4xl font-bold leading-[54px] text-slate-400 max-md:max-w-full">
          Veja o guia definitivo para conquistar seus objetivos como DEV em 2022
        </h1>
        <p className="mt-9 leading-7 text-purple-50 max-md:max-w-full">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh nibh eu
          in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed
          tristique placerat hac.
        </p>
        <Link
          href="#"
          className="mt-8 flex gap-2.5 self-start whitespace-nowrap text-lg font-bold leading-[150%] text-white"
        >
          Veja mais
          <div className="relative aspect-square w-6">
            <Image
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0d5950397b3b1b6fd0ff6fc077cfee47b1df003dcf349d2ef178ad1b992d5d1a?apiKey=5503bfd9e2fe4e73b2f967c9116ec022&"
              alt="Arrow Right"
              layout="fill"
              objectFit="contain"
            />
          </div>
        </Link>
      </article>
      <aside className="ml-5 flex w-6/12 flex-col max-md:ml-0 max-md:w-full">
        <div className="relative aspect-[1.64] w-full grow max-md:mt-10 max-md:max-w-full">
          <Image
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6ec4956de352a74c60ab291b44935d39b9570147d254db46b3db787afa762cf9?apiKey=5503bfd9e2fe4e73b2f967c9116ec022"
            alt="Hero Image"
            layout="fill"
            objectFit="contain"
          />
        </div>
      </aside>
    </section>
  );
}
